# Generated by Django 4.0.4 on 2022-05-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='Créditos',
            new_name='creditos',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='Name',
            new_name='nombre',
        ),
    ]
