# Generated by Django 4.0.4 on 2022-05-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_rename_créditos_curso_creditos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='creditos',
            new_name='credito',
        ),
    ]
