# Generated by Django 4.0.4 on 2022-05-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0004_rename_credito_curso_creditos_alter_curso_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='creditos',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
